### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by freekmurze** [laravel-notification-channels/twilio#1]
@gregoriohc Ping me here when you're ready with your package. Then I'll do a code review.

**Comment by gregoriohc** [comment]
Hi @freekmurze,
The first working version is now ready :)

**Comment by freekmurze** [comment]
Code review done. You did a good job. I only made some small changes. Also the fact that your provided some tests is highly appreciated.

Could you please retest the package in your app to ensure it still works after my changes?

If I've done anything you don't like, reopen this issue and let me know.

**Comment by gregoriohc** [comment]
The changes are OK. Great job of cleaning and refactoring :)
The tests are passing.
