### ISSUE TITLE
400 Error Laravel 7.4

### ISSUE THREAD

**Issue by tominal** [laravel-notification-channels/twilio#106]
I don't know what the deal is with this package so I went ahead and made a custom channel instead.

It is trying to use the "From" number instead of the model-defined phone number.

```
[HTTP 400] Unable to create record: The 'To' number +1[REDACTED] is not a valid phone number.
```

Everything is set up correctly according to the docs.

**Comment by atymic** [comment]
> I don't know what the deal is with this package so I went ahead and made a custom channel instead.


Not sure what you mean here?
Is the number you are sending to valid? Can't tell as you redacted it.
