### ISSUE TITLE
How to disable twilio sending sms during phpunit testing?

### ISSUE THREAD

**Issue by ajcastro** [laravel-notification-channels/twilio#120]
Hi there!

How to disable twilio sending sms during phpunit testing?

**Comment by atymic** [comment]
Modify your `routeNotificationsFor` method to return null if you're in the testing env.

**Comment by ajcastro** [comment]
@atymic that does not work because the `TwilioChannel::getTo()` checks the user if it has phone_number and returns it causing it to still send the sms.

**Comment by ajcastro** [comment]
@atymic I sent a PR. Hope it helps. Thanks!
