### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by lrljoe** [laravel-notification-channels/twilio#141]
Notice there's a couple of PRs open, including the upgrade to the newer SDK.

I've got a few feature improvements in flight, but want to know if this is maintained before I follow through.

**Comment by onlime** [comment]
Hope to get this package in shape again soon, #148

**Comment by lrljoe** [comment]
Let me know if I can assist, as at current am using a private fork

**Comment by onlime** [comment]
> Let me know if I can assist, as at current am using a private fork

Thanks @lrljoe !
I have just released [onlime/laravel-twilio v4.0.0](https://github.com/onlime/laravel-twilio/releases/tag/v4.0.0). Feel free to PR to that new repo. Would be happy if you'd contribute.

**Comment by lrljoe** [comment]
@onlime I would suggest that you reach out to the laravel-notification-channel crew, and get them to add you in.

I personally wouldn't start using another fork rather than just maintaining it myself (no offence!), as I've seen many forked repos die a similar death.

If you reach out to the laravel-notification-channel crew, then I'm sure they'll swap "twilio"  to your branch

It does feel a bit like the day of laravel-notification-channels has almost gone, given how many of the repos are now stale!

**Comment by lrljoe** [comment]
@atymic  - can we get this swapped over to [onlime/laravel-twilio v4.0.0](https://github.com/onlime/laravel-twilio/releases/tag/v4.0.0) so that it's maintained please?  Feels very abandoned!

**Comment by onlime** [comment]
@lrljoe you're absolutely right, I'd also prefer maintaining the official package instead of running my own fork. @atymic has already responded on https://github.com/laravel-notification-channels/twilio/pull/148#issuecomment-2495379649, so we got some progress here!

**Comment by onlime** [comment]
I have just released [v4.0.0](https://github.com/laravel-notification-channels/twilio/releases/tag/4.0.0)
