### ISSUE TITLE
Update twilio/sdk To Version 8

### ISSUE THREAD

**Issue by kellerjmrtn** [laravel-notification-channels/twilio#145]
Unsure if this package is still being actively maintained, but `twilio/sdk` [has released version 8](https://github.com/twilio/twilio-php/releases/tag/8.0.1). It may be worth bumping the dependency here to allow projects to update.

Oddly, the [upgrade guide](https://github.com/twilio/twilio-php/blob/8.0.0/UPGRADE.md#2023-03-25-7xx-to-8xx) claims to not have breaking changes:

>  We ensured that you can upgrade to Php helper Library 8.0.0 version without any breaking changes of existing apis

However the [changelog](https://github.com/twilio/twilio-php/blob/main/CHANGES.md) directly states otherwise

> https://github.com/twilio/twilio-php/pull/803: Merge 8.0.0-rc into main. Thanks to [@tiwarishubham635](https://github.com/tiwarishubham635)! (breaking change)

So I'm not sure what's going on there. Also potentially relevant #140

**Comment by onlime** [comment]
I have just released [v4.0.0](https://github.com/laravel-notification-channels/twilio/releases/tag/4.0.0)
