### ISSUE TITLE
Twilio SDK 5+

### ISSUE THREAD

**Issue by troygilbert** [laravel-notification-channels/twilio#18]
Twilio has deprecated their 4.x SDKs and will discontinue support for them on November 30. Any plans for upgrading to the 5.x SDK?

https://www.twilio.com/docs/libraries/php

**Comment by lnpbk** [comment]
@troygilbert I've actually made this change in my pull request, along with a few other changes.

https://github.com/laravel-notification-channels/twilio/pull/15

Looking for some more people to test the fork, and hopefully a response about merging it

**Comment by ejunker** [comment]
Would love to see this support Twilio SDK 5.*

**Comment by atapatel** [comment]
+1

**Comment by gregoriohc** [comment]
A new 2.0 version has been relased
