### ISSUE TITLE
Any plans to upgrade for 5.4?

### ISSUE THREAD

**Issue by REBELinBLUE** [laravel-notification-channels/twilio#20]
I can look into doing it if desired but if someone is already doing it I can wait?

**Comment by reddinan** [comment]
I would also be willing to do this but don't want to waste time if someone else is handling it.

**Comment by REBELinBLUE** [comment]
I've actually done it, I've had to fork 6 packages to be able to upgrade. I will submit a PR after I test it this evening but it looks like it is simply the version requirement in composer.json which needs updating

**Comment by reddinan** [comment]
Awesome! I will keep an eye out for this and also give it a once over.  My use case is very simple, though

**Comment by ghost** [comment]
+1 Need this ASAP.

```
laravel-notification-channels/twilio v1.0.1 requires illuminate/support 5.1.*|5.2.*|5.3.*
```

**Comment by REBELinBLUE** [comment]
I submitted a PR yesterday

**Comment by apoca** [comment]
I can't use this service on laravel 5.4..

BindingResolutionException in Container.php line 819:
Unresolvable dependency resolving [Parameter #0 [ <required> $sid ]] in class Services_Twilio

**Comment by REBELinBLUE** [comment]
Working fine for me on 5.4, did you remember to see the values in `.env` ?

**Comment by apoca** [comment]
I can't install version 1.0.1 ... 

- don't install illuminate/notifications v5.3.0|don't install laravel/framework v5.4.0
    - don't install illuminate/notifications v5.3.16|don't install laravel/framework v5.4.0
    - don't install illuminate/notifications v5.3.23|don't install laravel/framework v5.4.0
    - don't install illuminate/notifications v5.3.4|don't install laravel/framework v5.4.0

So I think this lib only work on laravel 5.3 can someone confirm? I'll do some tests..

**Comment by REBELinBLUE** [comment]
1.0.2 is the version for Laravel 5.4

**Comment by erikpolder** [comment]
I also get the following error:

`Unresolvable dependency resolving [Parameter #0 [ <required> $sid ]] in class Services_Twilio
`
I have set config + .env. The config variables getting through to the service provider. Any idea?

**Comment by REBELinBLUE** [comment]
Hmm actually yeah I am getting the same issue as well now. I shall investigate

**Comment by REBELinBLUE** [comment]
Oh, I see why, Laravel 5.4 changed the make method on the container. Not sure how it ever worked for me :| I will do a new PR to fix it

**Comment by REBELinBLUE** [comment]
Submitted a PR with the fix https://github.com/laravel-notification-channels/twilio/issues/24

If anyone uses `composer-patches` in composer you can use this URL to patch it https://www.phpdeployment.org/patches/0003-dependency-resolution-bug.patch
