### ISSUE TITLE
NotificationFailed is not fired when used in Lumen

### ISSUE THREAD

**Issue by bezruki** [laravel-notification-channels/twilio#23]
If sending a twilio message results in an exception, this is how the current code triggers event dispatching:

```
$this->events->fire(
                new NotificationFailed($notifiable, $notification, 'twilio', ['message' => $exception->getMessage()])
            );
```

This doesn't seem actually fire an event when the package is used in Lumen (my guess is that it's because unlike Laravel, Lumen uses `Laravel\Lumen\Providers\EventServiceProvider`)

When I replace the event firing with this `event(new NotificationFailed($notifiable, $notification, 'twilio', ['message' => $exception->getMessage()]));` - it starts working as expected. Any ideas/recommendations?

**Comment by gregoriohc** [comment]
This should be fixed on release 2.0.2
