### ISSUE TITLE
Driver Not Supported

### ISSUE THREAD

**Issue by djrausch** [laravel-notification-channels/twilio#33]
Using Laravel 5.5.1, I get the following error when trying to use the Twilio Notification channel.

`InvalidArgumentException: Driver [NotificationChannels\Twilio\TwilioChannel] not supported. in /home/vagrant/Code/projectname/vendor/laravel/framework/src/Illuminate/Support/Manager.php:91`

**Comment by jaspalt** [comment]
same. Anyone maintaining this driver?

**Comment by fwartner** [comment]
I’ll look over it later this day...

**Comment by jaspalt** [comment]
Also when queuing notifications, Twilio sms doesn't get sent. Queue runs it; however.

**Comment by weklund** [comment]
+1

**Comment by ghost** [comment]
@jaspalt Some news about the queue problem ? I've the same problem.

**Comment by fwartner** [comment]
Sorry for the delay. Updates are on the way later today :/

**Comment by gregoriohc** [comment]
I guess this is not happening anymore. I have tested it on Laravel 5.5 and 5.6 and it's working.
I anyone is still having problems, I will reopen this issue.

**Comment by Saif-hub24** [comment]
Yes i have the same problem.I am using laravel 5.6

**Comment by pixelplant** [comment]
This still happens with the latest versions of Laravel 5.8. Is this package dead?

**Comment by gregoriohc** [comment]
A lot of people is using this driver without any problem.
Are you sure is not a configuration problem?
Can you send an example of your code?

**Comment by pixelplant** [comment]
@gregoriohc Are they on Laravel 5.8 though? It worked fine until we upgraded from 5.7 to 5.8. Nothing has changed in our config except for updating to the latest version of the Twilio/Sdk and the latest version of laravel-notification-channels/twilio

Regarding the code used you can see it in this issue => https://github.com/laravel-notification-channels/twilio/issues/59
