### ISSUE TITLE
Support for Laravel 5.6

### ISSUE THREAD

**Issue by jdavidbakr** [laravel-notification-channels/twilio#36]
Just tried to update a project to Laravel 5.6 and am getting a compatibility error.  Given the change log for 5.6, I'm guessing that there are not any breaking changes and 5.6 can be added to the requirement composer.json file.

**Comment by jdavidbakr** [comment]
Pull request https://github.com/laravel-notification-channels/twilio/pull/37

**Comment by jdavidbakr** [comment]
There are 2 pull requests waiting to resolve this issue, any chance we can get them merged soon?

**Comment by fwartner** [comment]
Merged.
