### ISSUE TITLE
Laravel 5.6 release

### ISSUE THREAD

**Issue by bryce13950** [laravel-notification-channels/twilio#39]
Is there a laravel 5.6 release scheduled at the moment? Master seems to work right now, but it would be nice to have an official release.

**Comment by NoelDavies** [comment]
**5.6 is released**, **master** has the relevant changes to support **Laravel 5.6**.
Just needs a tag 😀

**Comment by gregoriohc** [comment]
New release (2.0.2) has Laravel 5.6 compatibility
