### ISSUE TITLE
Laravel 5.7 Support

### ISSUE THREAD

**Issue by zek** [laravel-notification-channels/twilio#45]

**Comment by jdavidbakr** [comment]
Pull request https://github.com/laravel-notification-channels/twilio/pull/46

**Comment by jdavidbakr** [comment]
Any update on when we might see this merged in and released?  This is holding up one of my projects from being updated to Laval 5.7.

**Comment by kalemdzievski** [comment]
5.7 Support would be great! Also looking forward for this one.

**Comment by gregoriohc** [comment]
It's merged now ;)
