### ISSUE TITLE
Support for Laravel 5.8

### ISSUE THREAD

**Issue by jdavidbakr** [laravel-notification-channels/twilio#52]

**Comment by jdavidbakr** [comment]
I see this has already been merged into master.

**Comment by pixelplant** [comment]
Could we have a 2.0.8 release though for this since it's easier to switch the version number in composer.json than switch to master.

Thanks

**Comment by fwartner** [comment]
Done :)

**Comment by gregoriohc** [comment]
Now it's updated on Packagist 😉
