### ISSUE TITLE
Better support for messagingServiceSid

### ISSUE THREAD

**Issue by harlan-zw** [laravel-notification-channels/twilio#54]
Overall there needs to be better support for `messagingServiceSid` sending.

Currently within the code the `from` string is required for any SMS. This is an issue if you're sending just using the messaging service, since no number is required for that. 

Also it would be good to be able to configure `messagingServiceSid` per message, instead of one global value. 

See the example here: https://www.twilio.com/docs/sms/services

**Comment by gregoriohc** [comment]
@loonpwn I have implemented this in the 2.0.10 release 😉
