### ISSUE TITLE
Update packagist notification

### ISSUE THREAD

**Issue by jdavidbakr** [laravel-notification-channels/twilio#56]
Github no longer supports the Github Services - which is how Packagist gets notified of new releases.  You have to convert it to a webhook.  Please update the notification process and also publish 2.0.8+ to packagist.

**Comment by gregoriohc** [comment]
> Github no longer supports the Github Services - which is how Packagist gets notified of new releases. You have to convert it to a webhook. Please update the notification process and also publish 2.0.8+ to packagist.

Yes, we know, thanks. The problem is that the only one with permissions to do that is @themsaid and he is not currently available to do it. I hope it will be done in a few days.

**Comment by gregoriohc** [comment]
Now it's updated 😉
