### ISSUE TITLE
On demand notifications doesn't work

### ISSUE THREAD

**Issue by conradwarhol** [laravel-notification-channels/twilio#58]
On-demand notifications (as [documented here](https://laravel.com/docs/5.6/notifications#on-demand-notifications)) does not seem to be working with this channel:

`\Notification::route(TwilioChannel::class, $phoneNumber)->notify(new MyNotification($data));`

Typical notifications with notifiable model work as expected:

`$user->notify(new MyNotification($data));`

Note: I am using a service_sid and not a from number in config. My laravel version is 5.6

Any ideas?

**UPDATE**

It works when i use "twilio" instead of class name:

`\Notification::route("twilio", $phoneNumber)->notify(new MyNotification($data));`

**Comment by Dahdoul** [comment]
Same issue here using Laravel 5.8

**Comment by conradwarhol** [comment]
I just checked and it works when i use "twilio" instead of class name:

`\Notification::route("twilio", $phoneNumber)->notify(new MyNotification($data));`

Maybe this behvaiour should be documented.

**Comment by atymic** [comment]
I'll try and investigate this when I have a chance.

**Comment by miken32** [comment]
This is because `TwilioChannel::getTo()` is doing this:
```php
        if ($notifiable->routeNotificationFor('twilio')) {
            return $notifiable->routeNotificationFor('twilio');
        }
```
