### ISSUE TITLE
InvalidArgumentException: Driver [NotificationChannels\Twilio\TwilioChannel] not supported in Laravel 5.8

### ISSUE THREAD

**Issue by pixelplant** [laravel-notification-channels/twilio#59]
Since we updated to Laravel 5.8 SMS notifications are not sent anymore in Queued notifications and we receive this error: "InvalidArgumentException: Driver [NotificationChannels\Twilio\TwilioChannel] not supported"

Using: Laravel 5.8.10
Twilio/Sdk: 5.31
laravel-notifications-twilio: 2.0.10

We have a general purpose notifications class that sends both emails and SMS messages. This worked fine before migrating to Laravel 5.8 and updating the twilio packages, but now only the emails are sent.

The constructor for our notification class:
```
    public function __construct($locale, $view, $subject, $options = [], $smsContent = '')
    {
        $this->locale     = $locale;
        $this->view       = $view;
        $this->subject    = $subject;
        $this->options    = $options;
        $this->smsContent = $smsContent;
    }
```

Here is how we set the **via** method in our GeneralNotification class:
```
use NotificationChannels\Twilio\TwilioChannel;
use NotificationChannels\Twilio\TwilioSmsMessage;

    /**
     * Get the notification's delivery channels.
     *
     * @param  mixed $notifiable
     *
     * @return array
     */
    public function via($notifiable)
    {
        $channels = [];
        if (isset($notifiable->routes['mail'])) {
            array_push($channels, 'mail');
        }
        if (isset($notifiable->routes['twilio'])) {
            array_push($channels, TwilioChannel::class);
        }

        return $channels;
    }
```

and the **toTwilio** call:
```
    /**
     * Send SMS message notifications
     *
     * @param $notifiable
     *
     * @return TwilioSmsMessage
     */
    public function toTwilio($notifiable)
    {
        app()->setLocale($this->locale);
        // grab the SMS recipient

        $notifiable->routes['twilio'] = format_phone($notifiable->routes['twilio'], true);
        $to = $notifiable->routes['twilio'];

        // remove HTML tags just in case we use the same translated text as in the email
        $smsMessage = strip_tags(__($this->smsContent, $this->options));
        Log::channel('notification_sms')->info("Sending SMS '$smsMessage' to: '$to'");
        return (new TwilioSmsMessage())
            ->from(config('app.twilio_from'))
            ->content($smsMessage);
    }
```

and this is how initiating this notification (GeneralNotification) would look like in code:
```
                                Notification::route('mail', 'test@test.com')
                                    ->route('twilio', '0790865237')
                                    ->notify(new GeneralNotification(
                                        'fr',
                                        'agent_reminder_agent_evaluation',
                                        'Meeting reminder',
                                        $options,
                                        'Reminder: you have a valuation visit scheduled tomorrow at for property in.'
                                    ));
```

Anyone having issues with this on Laravel 5.8? The notification **implements ShouldQueue**

Thanks

**Comment by pixelplant** [comment]
so it seems it was a composer issue.
One of the packages (owen-it/laravel-auditing) was still using a version made for laravel 5.7 and not 5.8 and I assume it did not manage to discover all the packages because of this. No error was displayed on screen though and installs and reinstalls runned without issues.
After I updated composer to use the right version, removed the "vendor" folder and did a ```composer clearcache``` followed by ```composer install``` made it running again

**Comment by anushrimathur** [comment]
[NotificationChannels\Twilio\TwilioChannel] Queued notifications are not working for me. Only mail got trigger but not the sms notification in laravel 5.7
