### ISSUE TITLE
How do you send whatsapp notification with this package. The TwilioSmsMessage does not work

### ISSUE THREAD

**Issue by HarshBachawat** [laravel-notification-channels/twilio#63]
I am unable to implement whatsapp notification with this package. Can someone please help me regarding the same.

**Comment by atymic** [comment]
It probably doesn't support it yet. You can check the docs and make a PR if you wish :)

**Comment by Mark-Howe** [comment]
Oldish issue, but Whatsapp sending is working fine for me.

Make sure you're prefacing the to/from numbers with _whatsapp:_, eg "whatsapp:+14155238886" for the sandbox.

**Comment by atymic** [comment]
Closing this :) Thanks @Mark-Howe
