### ISSUE TITLE
Queued SMS notification fails to send sms but send the mail. 

### ISSUE THREAD

**Issue by anushrimathur** [laravel-notification-channels/twilio#64]
Queued SMS notification fails to send sms when we use this channel. Anyone who implemented it please help to sort that out.

**Comment by atymic** [comment]
Can you post the errors you are having?

**Comment by cgesbenin** [comment]
I had the same problem, had to use Dispatchable in my notification:
`namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Notification;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use NotificationChannels\Twilio\TwilioChannel;
use NotificationChannels\Twilio\TwilioSmsMessage;
use Illuminate\Notifications\Messages\MailMessage;

class EventCreatedNotification extends Notification implements ShouldQueue
{
    use Dispatchable, Queueable;`

Now it's working properly with mail and Twilio..

Hope this can help someone...

**Comment by ronssij** [comment]
@atymic A am also experiencing this issue.

> public function via($notifiable)
>  {
>                 $isMail = $notifiable->notification_preference === 'mail';
>                 return $isMail ? ['mail'] : [TwilioChannel::class];
>  }

every time when you add `implements ShouldQueue`
the `[TwilioChannel::class]` won't work but if you remove the `implements ShouldQueue`
it works

**Comment by bruno-rodrigues** [comment]
@ronssij How are you triggering the notification? [On-demand](https://laravel.com/docs/7.x/notifications#on-demand-notifications)?

**Comment by jerome-embate** [comment]
Hi @anushrimathur It seems `use SerializesModels` was the solution, I tried it and it's working.

It will be helpful to add this on the docs for future reference.

Got the solution from [here](https://github.com/laravel/framework/issues/20628)
