### ISSUE TITLE
Update for Laravel 6.0?

### ISSUE THREAD

**Issue by pixelplant** [laravel-notification-channels/twilio#66]
Can we get an updated composer.json for Laravel 6 pls?

Thank you

**Comment by jdavidbakr** [comment]
PR https://github.com/laravel-notification-channels/twilio/pull/67

**Comment by alasdairw** [comment]
I'm not sure this is working?  At present, even if I install dev-master for this project, I am getting laravel-notification-channels/twilio dev-master requires illuminate/queue ^5.1 and a failure to install.

**Comment by vincentdh** [comment]
Same problem here.  Packagist does not see new version and did not update the dev-master.

**Comment by kalemdzievski** [comment]
Any updates on this? When is this package getting a support for 6.0?

**Comment by pixelplant** [comment]
@kalemdzievski If you use "dev-master" in your composer.json file it should work. I just updated our project today and it works fine with Laravel 6

**Comment by neppoz** [comment]
Hi, i confirm that the install worked for me:
composer require laravel-notification-channels/twilio:**dev-master**

Thank you for support

**Comment by atymic** [comment]
Github hooks should be syncing with packagist properly now. If there are any issues in the future ping me 😄

**Comment by vincentdh** [comment]
@atymic as 2.0.10 is not compatible with Laravel 6, can I suggest to create a new release like 2.0.11 
 instead of working with dev-master?

**Comment by atymic** [comment]
My bad @vincentdh 

Tagged `2.0.11` :)
