### ISSUE TITLE
Local Development Support

### ISSUE THREAD

**Issue by klimov-paul** [laravel-notification-channels/twilio#72]
There should be better support for local development in the same way [Laravel provide for mail](https://laravel.com/docs/6.x/mail#mail-and-local-development).

* It would be nice to be able writing SMS content into a log file instead of actually sending them to Twilio. So actual SMS content can be viewed, URLs picker up and so on.

* It would be nice to have a setting for the universal receiver - a single phone number, which should receive all notifications. This is a crucial feature for the project QA.

**Comment by klimov-paul** [comment]
Having some kind of `NullDriver` will also come in handy while writing project unit tests, avoiding unnecessary Twilio API calls.

**Comment by atymic** [comment]
Released in v3 🎉
https://github.com/laravel-notification-channels/twilio/releases/tag/3.0.0
