### ISSUE TITLE
Remove usage of `NotificationFailed`

### ISSUE THREAD

**Issue by klimov-paul** [laravel-notification-channels/twilio#74]
Relates to #60.

I suppose usage of `Illuminate\Notifications\Events\NotificationFailed` event serves no purpose.
It complicates the source code without any significant outcome.

Class `NotificationFailed` is **never** used inside the Laravel Framework itself, despite it declares it.
It would be more consistent to drop its usage around this library.

**Comment by atymic** [comment]
See #90

**Comment by atymic** [comment]
Released in v3 🎉
https://github.com/laravel-notification-channels/twilio/releases/tag/3.0.0

**Comment by clod986** [comment]
Still in `TwilioChannel` @ line61, is this intentional?
