### ISSUE TITLE
Update to Twilio latest version 6.0

### ISSUE THREAD

**Issue by shahvirag** [laravel-notification-channels/twilio#78]
https://github.com/twilio/twilio-php/releases/tag/6.0.0

**Comment by atymic** [comment]
Happy to accept a PR

**Comment by m1stermanager** [comment]
they added a _bunch_ of return types and its way more of a hassle than I would really anticipate. I am attempting this now but it might require somebody much more familiar w/ one or both libraries

edit w/ a bit more detail:
in a PR from @shahvirag's link, they basically start enforcing that things are either instances of their CallInstance or MessageInstance classes and right now everything is an extension of the TwilioMessage class, which extends neither and obviously can't extend both. It might end up being a fairly extensive set of changes. I have some idea but I don't know how awful either approach is. 

additional edit:
I think the real problem isn't w/ the types in this package but rather, I need to learn mockery better. 

final edit:
i found the problem and it was far more obvious than I care to admit. I'm only a little crazy perhaps. 

PR coming shortly if all goes well.

**Comment by m1stermanager** [comment]
#89 is ready for review

**Comment by atymic** [comment]
Closed  in #90

**Comment by atymic** [comment]
Released in v3 🎉
https://github.com/laravel-notification-channels/twilio/releases/tag/3.0.0
